AWSTemplateFormatVersion: '2010-09-09'
Description: SES Email Receiving Setup

Parameters:
  SystemCode:
    Type: "String"
  SystemEnv:
    Type: "String"

Resources:
  IAMRoleSESReceiptRule:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "role-${SystemCode}-${SystemEnv}-receipt-rule"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ses.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: S3Access
                Effect: Allow
                Action: s3:PutObject
                Resource: !Sub "arn:aws:s3:::s3-${SystemCode}-${SystemEnv}-ses/*"

  SESReceiptRuleSet:
    Type: "AWS::SES::ReceiptRuleSet"
    Properties:
      RuleSetName: !Sub "ses-${SystemCode}-${SystemEnv}-receipt-ruleset"

  SESReceiptRule:
    Type: "AWS::SES::ReceiptRule"
    Properties:
      RuleSetName: !Ref SESReceiptRuleSet
      Rule:
        Name: ReceiveRule
        Enabled: true
        Recipients:
          - !Sub "{{resolve:ssm:param-${SystemCode}-${SystemEnv}-hostedzone-name}}"
        Actions:
          - S3Action:
              BucketName: !Sub "s3-${SystemCode}-${SystemEnv}-ses"
              ObjectKeyPrefix: "emails/"
              IamRoleArn: !GetAtt IAMRoleSESReceiptRule.Arn
        ScanEnabled: true
        TlsPolicy: Optional

  SESDomainIdentity:
    Type: "AWS::SES::EmailIdentity"
    Properties:
      EmailIdentity: !Sub "{{resolve:ssm:param-${SystemCode}-${SystemEnv}-hostedzone-name}}"
      DkimAttributes:
        SigningEnabled: true

  DKIMRecord1:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Sub "{{resolve:ssm:param-${SystemCode}-${SystemEnv}-hostedzone-id}}"
      Name: !GetAtt SESDomainIdentity.DkimDNSTokenName1
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - !GetAtt SESDomainIdentity.DkimDNSTokenValue1

  DKIMRecord2:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Sub "{{resolve:ssm:param-${SystemCode}-${SystemEnv}-hostedzone-id}}"
      Name: !GetAtt SESDomainIdentity.DkimDNSTokenName2
      Type: CNAME
      TTL: 1800
      ResourceRecords:
        - !GetAtt SESDomainIdentity.DkimDNSTokenValue2

  DKIMRecord3:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Sub "{{resolve:ssm:param-${SystemCode}-${SystemEnv}-hostedzone-id}}"
      Name: !GetAtt SESDomainIdentity.DkimDNSTokenName3
      Type: CNAME
      TTL: 1800
      ResourceRecords:
        - !GetAtt SESDomainIdentity.DkimDNSTokenValue3

  MXRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Sub "{{resolve:ssm:param-${SystemCode}-${SystemEnv}-hostedzone-id}}"
      Name: !Sub "{{resolve:ssm:param-${SystemCode}-${SystemEnv}-hostedzone-name}}"
      Type: MX
      TTL: 1800
      ResourceRecords:
        - !Sub "10 inbound-smtp.${AWS::Region}.amazonaws.com"

Outputs:
  SESReceiptRuleSet:
    Value: !Ref SESReceiptRuleSet
    Export:
      Name: !Sub "ses-${SystemCode}-${SystemEnv}-receipt-ruleset"